# Set update schedule for GitHub Actions

version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels: ["no changelog", "merge when ready", "dependencies", "github_actions"]
    schedule:
      interval: "weekly"
