[[constraint]]
  name = "github.com/google/go-github"
  revision = "511f540f1887d30b88cee4a2fcd1f2922754acf4"

[[constraint]]
  name = "github.com/ipfans/echo-session"
  version = "3.1.1"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.2.3"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "github.com/spf13/cobra"
  revision = "e5f66de850af3302fbe378c8acded2b0fa55472c"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "golang.org/x/oauth2"
  revision = "bb50c06baba3d0c76f9d125c0719093e315b5b44"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.7.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  revision = "eb3733d160e74a9c7e442f435eb3bea458e1d19f"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.0.0"
