{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "bulldozer-bot.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "bulldozer-bot.labels" . | indent 4 }}
rules:
- apiGroups: [""]
  resources: [""]
  verbs: [""]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "bulldozer-bot.fullname" . }}
  labels:
{{ include "bulldozer-bot.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "bulldozer-bot.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "bulldozer-bot.serviceAccountName" .}}
  namespace: {{ .Release.Namespace }}
{{ end }}
