{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bulldozer-bot.serviceAccountName" . }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
{{ end }}
  labels:
{{ include "bulldozer-bot.labels" . | indent 4 }}
{{ end }}
