# Options for the http server
server:
  # The listen address. Can also be set by the BULLDOZER_ADDRESS environment
  # variable.
  address: "0.0.0.0"
  # The listen port. Can also be set by the BULLDOZER_PORT environment
  # variable.
  port: 8080
  # Uncomment the "tls_config" block to enable HTTPS support in the server.
  # The cert and key files must be usable by net/http.ListenAndServeTLS().
  # Cert and Key file can also be set by the BULLDOZER_TLS_CERT_FILE and
  # BULLDOZER_TLS_KEY_FILE environment variables, respectively.
  # tls_config:
  #   cert_file: /path/to/server.pem
  #   key_file: /path/to/server.key

# Options for logging output
logging:
  # If true, logs are printed in human-readable form. We recommend using
  # "false" to output JSON-formatted logs in production
  text: false

  # Set a minimum logging level threshold
  # Choose from: debug, info, warn, error
  level: debug

# Options for the GitHub response cache. When the cache reaches max_size, the
# oldest entries are evicted. Size properties can use any format supported by
# https://github.com/c2h5oh/datasize
#
# cache:
#   max_size: "50MB"

# Options for webhook processing workers. Events are dropped if the queue is
# full. The defaults are shown below.
#
# workers:
#   workers: 10
#   queue_size: 100

# Options for connecting to GitHub
github:
  # The URL of the GitHub homepage. Can also be set by the GITHUB_WEB_URL
  # environment variable.
  web_url: "https://github.com"
  # The base URL for v3 (REST) API requests. Can also be set by the
  # GITHUB_V3_API_URL environment variable.
  v3_api_url: "https://api.github.com"
  app:
    # The integration ID of the GitHub app. Can also be set by the
    # GITHUB_APP_INTEGRATION_ID environment variable.
    integration_id: 1
    # A random string used to validate webhooks. Can also be set by the
    # GITHUB_APP_WEBHOOK_SECRET environment variable.
    webhook_secret: "app_secret"
    # The private key of the GitHub app (.pem file download from GitHub). Can
    # also be set by the GITHUB_APP_PRIVATE_KEY environment variable.
    private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      xxxxx
      xxxxx
      xxxxx
      -----END RSA PRIVATE KEY-----

# Options for application behavior
options:
  # The path within repositories to find the bulldozer.yml config file
  configuration_path: .bulldozer.yml

  # The name of the application. This will affect the User-Agent header
  # when making requests to Github.
  app_name: bulldozer

  # Deprecated: An optional personal access token associated with a GitHub user
  # that is used to merge pull requests into protected branches with push
  # restrictions. Can also be set by the BULLDOZER_PUSH_RESTRICTION_USER_TOKEN
  # environment variable.
  #
  # This is not necessary on GitHub.com and GitHub Enterprise 2.20+, which
  # allow applications in the push restriction list.
  #
  # push_restriction_user_token: token

  # A default repository configuration to use if a repository does not define a
  # configuration. The format is the same as the bulldozer.yml file. If unset
  # (the default), Bulldozer ignores repositories that are missing a
  # configuration file.
  #
  # default_repository_config:
  #   merge:
  #     ignore:
  #       labels: ["do not merge"]

# Optional configuration to emit metrics to datadog
datadog:
  # Database endpoint
  address: "127.0.0.1:8125"
  # The metric flush frequency. Accepts any string
  # parseable by https://golang.org/pkg/time/#ParseDuration
  interval: "10s"
  # Tags to include
  tags:
    - "bulldozer"
