version: 1

merge:
  whitelist:
    labels: ["merge when ready"]
    comment_substrings: ["==MERGE_WHEN_READY=="]
  blacklist:
    labels: ["do not merge"]
    comment_substrings: ["==DO_NOT_MERGE=="]
  method: squash
  options:
    squash:
      body: summarize_commits
  delete_after_merge: true

update:
  whitelist:
    labels: ["wip", "update me"]
